name: github-action-runner-tests
on: push
jobs:
  Ubuntu-ARM64:
    runs-on: [ubuntu-latest, ARM64]
    steps:
      - name: ubuntu-latest-arm64
      - run: echo "ubuntu-latest arm64"
      - run: lsb_release -a
      - run: lscpu

  Ubuntu-ARM64-GPU:
    runs-on: [ubuntu-latest, ARM64, gpu]
    steps:
      - name: ubuntu-latest-arm64-gpu
      - run: echo "ubuntu-latest arm64"
      - run: lsb_release -a
      - run: lscpu

  Ubuntu-x64:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: ubuntu-latest-arm64
      - run: echo "ubuntu-latest arm64"
      - run: lsb_release -a
      - run: lscpu
        
  Ubuntu-x64-GPU:
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - name: ubuntu-latest-arm64-gpu
      - run: echo "ubuntu-latest arm64 gpu"
      - run: lsb_release -a
      - run: lscpu
        
  Windows-ARM64:
    runs-on: [windows-latest, ARM64]
    steps:
      - name: windows-latest-arm64
      - run: echo "windows-latest arm64"
      - run: ver
      - run: wmic cpu get name

  Windows-ARM64-GPU:
    runs-on: [windows-latest, ARM64, gpu]
    steps:
      - name: windows-latest-arm64-gpu
      - run: echo "windows ARM64 GPU"
      - run: ver
      - run: wmic cpu get name

  Windows-x64:
    runs-on: [windows-latest, x64]
    steps:
      - name: windows-latest-x64
      - run: echo "windows"
      - run: ver
      - run: wmic cpu get name

  Windows-x64-GPU:
    runs-on: [windows-latest, x64, gpu]
    steps:
      - name: windows-latest-x64-gpu
      - run: echo "windows"
      - run: ver
      - run: wmic cpu get name

  MacOS-ARM64:
    runs-on: [macos-latest, ARM64]
    steps:
      - name: macos-latest-arm64
      - run: echo "macos-latest"
      - run: sw_vers
      - run: sysctl -a | grep brand
      - run: sysctl -n hw.ncpu

  MacOS-ARM64-GPU:
    runs-on: [macos-latest, ARM64, gpu]
    steps:
      - name: macos-latest-arm64-gpu
      - run: echo "macos-latest gpu"
      - run: sw_vers
      - run: sysctl -a | grep brand
      - run: sysctl -n hw.ncpu
    
