name: github-test-runner-tests
on: push
jobs:
  Ubuntu-ARM64:
    runs-on:
      [ubuntu-latest, ARM64]
    steps:
      - name: ubuntu-latest-arm64
        run: 
          echo "ubuntu-latest arm64"
          lsb_release -a
          lscpu

  Ubuntu-x64:
    runs-on:
      [self-hosted, linux, x64]
    steps:
      - name: ubuntu-latest-arm64
        run: 
          echo "ubuntu-latest arm64"
          lsb_release -a
          lscpu
        
  Ubuntu-x64-gpu:
    runs-on:
      [self-hosted, linux, x64, gpu]
    steps:
      - name: ubuntu-latest-arm64-gpu
        run: 
          echo "ubuntu-latest arm64 gpu"
          lsb_release -a
          lscpu
        
  Windows-ARM64:
    runs-on:
      [windows-latest, ARM64]
      
    steps:
      - name: windows-latest-arm64
        run:
          echo "windows-latest arm64"
          ver
          wmic cpu get name

  Windows-ARM64-gpu:
    runs-on:
      [windows-latest, ARM64, gpu]
      
    steps:
      - name: windows-latest-arm64-gpu
        run:
          echo "windows ARM64 GPU"
          ver
          wmic cpu get name

  Windows-x64:
    runs-on:
      [windows-latest, x64]
      
    steps:
      - name: windows-latest-x64
        run:
          echo "windows"
          ver
          wmic cpu get name

  Windows-x64-gpu:
    runs-on:
      [windows-latest, x64, gpu]
      
    steps:
      - name: windows-latest-x64-gpu
        run:
          echo "windows"
          ver
          wmic cpu get name

  MacOS-ARM64:
    runs-on:
      [macos-latest, ARM64]
      
    steps:
      - name: macos-latest-arm64
        run: 
          echo "macos-latest"
          sw_vers
          sysctl -a | grep brand
          sysctl -n hw.ncpu

  MacOS-ARM64-GPU:
    runs-on:
      [macos-latest, ARM64, gpu]
      
    steps:
      - name: macos-latest-arm64-gpu
        run: 
          echo "macos-latest gpu"
          sw_vers
          sysctl -a | grep brand
          sysctl -n hw.ncpu
    
